### ISSUE TITLE
JSX element type 'TimeAgo' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by martin-braun** [hustcc/timeago-react#29]
I get an error on the TimeAgo component in SPFX TSX React:

![Screenshot 2020-05-06 at 17 18 38](https://user-images.githubusercontent.com/24259245/81195623-63413f00-8fbe-11ea-8fc4-c676dd05cd0b.png)
```
JSX element type 'TimeAgo' is not a constructor function for JSX elements.
  Type 'TimeAgo' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.
```
The return type of the function above is `JSX.Element`.

I think this issue is related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544, but it should be able to bypass this.

**Comment by alanwei0** [comment]
@martin-braun Could you provide us how you imported TimeAgo?

**Comment by martin-braun** [comment]
> @martin-braun Could you provide us how you imported TimeAgo?

```bash
npm i timeago-react
```

and in the head of my webpart file: 

```ts
import TimeAgo from 'timeago-react';
```

**Comment by alanwei0** [comment]
@martin-braun 
I think your code is correct, but I really don't know why you came across the error. Could you give us more details or directly give us your proposed fix?

**Comment by martin-braun** [comment]
> @martin-braun
> I think your code is correct, but I really don't know why you came across the error. Could you give us more details or directly give us your proposed fix?

We use this TimeAgo component in a new product we haven't sold, yet. So we dropped it for now and use static mockup strings for the time column in that list we use this component at.

Please keep this issue open for now. I will get back to you. In case we sold the product, I will supply a test project, so you can reproduce the issue, otherwise I will respond here that we don't need a fix, right now. In that case I will close this issue.

**Comment by mxmind** [comment]
Hi @martin-braun, the quick solution to fix your issue is:

```js
const TypeAgoFixed = (TimeAgo as unknown) as React.Component<TimeAgoProps>
    & { new(props): React.Component<TimeAgoProps> };
```
Then, you can use TypeAgoFixed as a normal React component.

```jsx
<TypeAgoFixed datetime={Date.now()} locale='en_US' />
```

**Comment by wangweixuan** [comment]
@alanwei0 
I've found the cause of the problem.

Current source code:
https://github.com/hustcc/timeago-react/blob/387a047d9df19205ce9a000de0f5ffcd70a4b92b/src/timeago-react.tsx#L1
However, the recommended way to import React is `import * as React from 'react';`. The above is the legacy way. In order to enable the legacy way, we have to use an option:
https://github.com/hustcc/timeago-react/blob/387a047d9df19205ce9a000de0f5ffcd70a4b92b/tsconfig.json#L9

But in my project, that option is not turned on, so TypeScript compiler would not recognize the above import, meaning `TimeAgo` class is not recognized as a React component.

I suggest that making a change to the import statement could solve this issue.
